name: Export Data to GCS

on:
  workflow_dispatch:
    inputs:
      result_name:
        description: 'Name for the result file'
        required: true
        default: 'results.csv'

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Run BigQuery Query and Export
        run: |
          # Run the SQL query from the file and export to CSV with the provided result name
          bq query --use_legacy_sql=false --format=csv < sit/query.sql > ${{ github.event.inputs.result_name }}

      - name: Upload to Google Cloud Storage
        run: |
          gsutil cp ${{ github.event.inputs.result_name }} gs://your-bucket-name/path/to/destination/
